### ISSUE TITLE
Client Side webcam not working on my phone

### ISSUE THREAD

**Issue by dnbfdhn** [whiteSHADOW1234/PetCam#1]
First, I run `npm start` in vscode, then copy the output url `Open Cam: https://<your_server_ip>:5000/client/open-cam` shown up in terminal and paste it to Brave browser in my android phone, but it won't connect. 
In addition, if I paste the url to my laptop it will use my cam and work fine.

**Comment by whiteSHADOW1234** [comment]
This issue was fixed in commit d20289c. The client-side webcam IP has been updated to `192.168.31.193`. 
Please try using this updated IP and let us know if it resolves your issue!
